project:
  type: website
  output-dir: "./_output"
  post-render: encrypt.r

website:
  title: "Telkom University"

format: dashboard
fig-width: 10
fig-asp: 0.3
theme: [sandstone, themes/dashboard.scss]



